-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-02 03:57:48 SGT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

set echo on
spool property_rental_schema.txt

DROP TABLE maintenance CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE payment CASCADE CONSTRAINTS;

DROP TABLE property CASCADE CONSTRAINTS;

DROP TABLE rent CASCADE CONSTRAINTS;

DROP TABLE tenant CASCADE CONSTRAINTS;

CREATE TABLE maintenance (
    maint_no               NUMBER NOT NULL,
    prop_no                NUMBER(7) NOT NULL,
    rent_lease_startdate   DATE NOT NULL,
    payment_no             NUMBER(7),
    maint_datetime         DATE NOT NULL,
    maint_desc             VARCHAR2(50) NOT NULL,
    maint_cost             NUMBER(7, 2) NOT NULL
);

COMMENT ON COLUMN maintenance.maint_no IS
    'Surrogate Key: Maintainence Number';

COMMENT ON COLUMN maintenance.prop_no IS
    'Property Number';

COMMENT ON COLUMN maintenance.rent_lease_startdate IS
    'Rent Lease Start Date';

COMMENT ON COLUMN maintenance.payment_no IS
    'Payment Number';

COMMENT ON COLUMN maintenance.maint_datetime IS
    'Maintenance Date & Time';

COMMENT ON COLUMN maintenance.maint_desc IS
    'Maintenance Description';

COMMENT ON COLUMN maintenance.maint_cost IS
    'Maintenance Cost ';

CREATE UNIQUE INDEX maintenance__idx ON
    maintenance (
        payment_no
    ASC );

ALTER TABLE maintenance ADD CONSTRAINT maintenance_pk PRIMARY KEY ( maint_no );

ALTER TABLE maintenance
    ADD CONSTRAINT nk_maintenance UNIQUE ( rent_lease_startdate,
                                           prop_no,
                                           payment_no,
                                           maint_datetime );

CREATE TABLE owner (
    owner_no        NUMBER(7) NOT NULL,
    owner_title     VARCHAR2(5) NOT NULL,
    owner_gname     VARCHAR2(20) NOT NULL,
    owner_fname     VARCHAR2(20) NOT NULL,
    owner_address   VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN owner.owner_no IS
    'Owner Number';

COMMENT ON COLUMN owner.owner_title IS
    'Owner Title';

COMMENT ON COLUMN owner.owner_gname IS
    'Owner Given Name';

COMMENT ON COLUMN owner.owner_fname IS
    'Owner Family Name';

COMMENT ON COLUMN owner.owner_address IS
    'Owner Address';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_no );

CREATE TABLE payment (
    payment_no             NUMBER(7) NOT NULL,
    payment_date           DATE NOT NULL,
    payment_type           VARCHAR2(20) NOT NULL,
    payment_amount         NUMBER(7, 2) NOT NULL,
    payment_paidby         VARCHAR2(50) NOT NULL,
    rent_lease_startdate   DATE NOT NULL,
    prop_no                NUMBER(7) NOT NULL
);

ALTER TABLE payment
    ADD CONSTRAINT "DROP DOWN LIST PAYMENT_TYPE" CHECK ( payment_type IN (
        'Bank Transfer',
        'Cash',
        'Credit/Debit Card'
    ) );

ALTER TABLE payment ADD CONSTRAINT "CHK PAYMENT AMOUNT" CHECK ( payment_amount >
0 );

COMMENT ON COLUMN payment.payment_no IS
    'Payment Number';

COMMENT ON COLUMN payment.payment_date IS
    'Payment Date';

COMMENT ON COLUMN payment.payment_type IS
    'Payment Type';

COMMENT ON COLUMN payment.payment_amount IS
    'Payment Amount';

COMMENT ON COLUMN payment.payment_paidby IS
    'Payment Paid By';

COMMENT ON COLUMN payment.rent_lease_startdate IS
    'Rent Lease Start Date';

COMMENT ON COLUMN payment.prop_no IS
    'Property Number';

ALTER TABLE payment ADD CONSTRAINT payment_pk PRIMARY KEY ( payment_no );

CREATE TABLE property (
    prop_no        NUMBER(7) NOT NULL,
    prop_address   VARCHAR2(50) NOT NULL,
    prop_value     NUMBER(7, 2) NOT NULL,
    owner_no       NUMBER(7) NOT NULL
);

COMMENT ON COLUMN property.prop_no IS
    'Property Number';

COMMENT ON COLUMN property.prop_address IS
    'Property Address';

COMMENT ON COLUMN property.prop_value IS
    'Property Value';

COMMENT ON COLUMN property.owner_no IS
    'Owner Number';

ALTER TABLE property ADD CONSTRAINT property_pk PRIMARY KEY ( prop_no );

CREATE TABLE rent (
    rent_lease_startdate   DATE NOT NULL,
    rent_weekly_rate       NUMBER(7, 2) NOT NULL,
    rent_bond              NUMBER(7, 2) NOT NULL,
    rent_lease_period      CHAR(5) NOT NULL,
    prop_no                NUMBER(7) NOT NULL,
    tenant_no              NUMBER(7) NOT NULL
);

ALTER TABLE rent ADD CONSTRAINT chk_weekly_rate CHECK ( rent_weekly_rate > 0 );

COMMENT ON COLUMN rent.rent_lease_startdate IS
    'Rent Lease Start Date';

COMMENT ON COLUMN rent.rent_weekly_rate IS
    'Rent Weekly Rate';

COMMENT ON COLUMN rent.rent_bond IS
    'Rent Bond(deposit)';

COMMENT ON COLUMN rent.rent_lease_period IS
    'Rent Lease ';

COMMENT ON COLUMN rent.prop_no IS
    'Property Number';

COMMENT ON COLUMN rent.tenant_no IS
    'Tenant Number';

ALTER TABLE rent ADD CONSTRAINT rent_pk PRIMARY KEY ( rent_lease_startdate,
                                                      prop_no );

CREATE TABLE tenant (
    tenant_no         NUMBER(7) NOT NULL,
    tenant_title      VARCHAR2(5) NOT NULL,
    tenant_gname      VARCHAR2(20) NOT NULL,
    tenant_fname      VARCHAR2(20) NOT NULL,
    tenant_street     VARCHAR2(50) NOT NULL,
    tenant_city       VARCHAR2(50) NOT NULL,
    tenant_state      VARCHAR2(50) NOT NULL,
    tenant_postcode   CHAR(5) NOT NULL,
    tenant_phone      CHAR(12) NOT NULL
);

COMMENT ON COLUMN tenant.tenant_no IS
    'Tenant Number';

COMMENT ON COLUMN tenant.tenant_title IS
    'Tenant Title';

COMMENT ON COLUMN tenant.tenant_gname IS
    'Tenant Given Name';

COMMENT ON COLUMN tenant.tenant_fname IS
    'Tenant Family Name';

COMMENT ON COLUMN tenant.tenant_street IS
    'Tenant Street';

COMMENT ON COLUMN tenant.tenant_city IS
    'Tenant City';

COMMENT ON COLUMN tenant.tenant_state IS
    'Tenant State';

COMMENT ON COLUMN tenant.tenant_postcode IS
    'Tenant Postcode';

COMMENT ON COLUMN tenant.tenant_phone IS
    'Tenant Phone Number ';

ALTER TABLE tenant ADD CONSTRAINT tenant_pk PRIMARY KEY ( tenant_no );

ALTER TABLE maintenance
    ADD CONSTRAINT damage_to_payment FOREIGN KEY ( payment_no )
        REFERENCES payment ( payment_no );

ALTER TABLE property
    ADD CONSTRAINT owner_to_property FOREIGN KEY ( owner_no )
        REFERENCES owner ( owner_no );

ALTER TABLE rent
    ADD CONSTRAINT property_to_rent FOREIGN KEY ( prop_no )
        REFERENCES property ( prop_no );

ALTER TABLE maintenance
    ADD CONSTRAINT rent_to_damage FOREIGN KEY ( rent_lease_startdate,
                                                prop_no )
        REFERENCES rent ( rent_lease_startdate,
                          prop_no );

ALTER TABLE payment
    ADD CONSTRAINT rent_to_payment FOREIGN KEY ( rent_lease_startdate,
                                                 prop_no )
        REFERENCES rent ( rent_lease_startdate,
                          prop_no );

ALTER TABLE rent
    ADD CONSTRAINT tenant_to_rent FOREIGN KEY ( tenant_no )
        REFERENCES tenant ( tenant_no );

spool off
set echo off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             1
-- ALTER TABLE                             16
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
