-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-01 17:02:08 SGT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

set echo on
spool customer_orders_schema.txt



DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE orderline CASCADE CONSTRAINTS;

DROP TABLE orders CASCADE CONSTRAINTS;

DROP TABLE product CASCADE CONSTRAINTS;

CREATE TABLE customer (
    cust_no        NUMBER(7) NOT NULL,
    cust_name      VARCHAR2(50) NOT NULL,
    cust_address   VARCHAR2(50) NOT NULL,
    cust_phone     CHAR(10)
);

COMMENT ON COLUMN customer.cust_no IS
    'customer number';

COMMENT ON COLUMN customer.cust_name IS
    'customer name';

COMMENT ON COLUMN customer.cust_address IS
    'Customer address';

COMMENT ON COLUMN customer.cust_phone IS
    'customer phone number';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( cust_no );

CREATE TABLE orderline (
    orderline_no    NUMBER(7) NOT NULL,
    ol_qtyordered   NUMBER(7) NOT NULL,
    ol_lineprice    NUMBER(7, 2) NOT NULL,
    prod_no         NUMBER(7) NOT NULL,
    order_no        NUMBER(7) NOT NULL
);

ALTER TABLE orderline ADD CONSTRAINT chk_ol_qtyordered CHECK ( ol_qtyordered > 0
);

COMMENT ON COLUMN orderline.ol_qtyordered IS
    'Quantityt Ordered';

COMMENT ON COLUMN orderline.ol_lineprice IS
    'Line Price';

COMMENT ON COLUMN orderline.prod_no IS
    'Product Number';

COMMENT ON COLUMN orderline.order_no IS
    'Order Number';

ALTER TABLE orderline ADD CONSTRAINT orderline_pkv1 PRIMARY KEY ( orderline_no );

ALTER TABLE orderline ADD CONSTRAINT nk_orderline UNIQUE ( prod_no,
                                                           order_no );

CREATE TABLE orders (
    order_no     NUMBER(7) NOT NULL,
    order_date   DATE NOT NULL,
    cust_no      NUMBER(7) NOT NULL
);

COMMENT ON COLUMN orders.order_no IS
    'Order Number';

COMMENT ON COLUMN orders.order_date IS
    'Order Date';

COMMENT ON COLUMN orders.cust_no IS
    'customer number';

ALTER TABLE orders ADD CONSTRAINT orders_pk PRIMARY KEY ( order_no );

CREATE TABLE product (
    prod_no          NUMBER(7) NOT NULL,
    prod_desc        VARCHAR2(50) NOT NULL,
    prod_unitprice   NUMBER(7, 2) NOT NULL
);

COMMENT ON COLUMN product.prod_no IS
    'Product Number';

COMMENT ON COLUMN product.prod_desc IS
    'Product Description';

COMMENT ON COLUMN product.prod_unitprice IS
    'Product unit price';

ALTER TABLE product ADD CONSTRAINT product_pk PRIMARY KEY ( prod_no );

ALTER TABLE orders
    ADD CONSTRAINT customer_orders FOREIGN KEY ( cust_no )
        REFERENCES customer ( cust_no );

ALTER TABLE orderline
    ADD CONSTRAINT orders_orderline FOREIGN KEY ( order_no )
        REFERENCES orders ( order_no );

ALTER TABLE orderline
    ADD CONSTRAINT product_orderline FOREIGN KEY ( prod_no )
        REFERENCES product ( prod_no );

spool off
set echo off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
