--****PLEASE ENTER YOUR DETAILS BELOW****
--Q2-tds-queries.sql
--Student ID:
--Student Name:
--Tutorial No: 

/* Comments for your marker:




*/
SELECT * FROM SUSPENSION;

/*
2(i) Query 1
*/
--PLEASE PLACE REQUIRED SQL STATEMENT FOR THIS PART HERE

SELECT 
    DEM_POINTS AS "Demerit Points",
    DEM_DESCRIPTION AS "Demerit Descriptions"
FROM
    DEMERIT
WHERE
    DEM_DESCRIPTION like '%Heavy%' or 
    DEM_DESCRIPTION like '%heavy%' or
    DEM_DESCRIPTION like 'Exceed%'
ORDER BY 
    DEM_POINTS, DEM_DESCRIPTION;


/*
2(ii) Query 2
*/
--PLEASE PLACE REQUIRED SQL STATEMENT FOR THIS PART HERE

SELECT
    VEH_MAINCOLOR AS "Main Colour",
    VEH_VIN AS VIN,
    TO_CHAR(VEH_YRMANUF, 'YYYY') AS "Year Manufactured"
FROM 
    VEHICLE
WHERE
    (TO_CHAR(VEH_YRMANUF, 'YYYY') >= '2012' AND TO_CHAR(VEH_YRMANUF, 'YYYY') <= '2014') AND
    (VEH_MODNAME = 'Range Rover' OR
    VEH_MODNAME = 'Range Rover Sport')
ORDER BY
    VEH_YRMANUF DESC, 
    VEH_MAINCOLOR ASC;

/*
2(iii) Query 3
*/
--PLEASE PLACE REQUIRED SQL STATEMENT FOR THIS PART HERE

SELECT
    D.LIC_NO AS "Licence No.",
    D.LIC_FNAME || ' ' || LIC_LNAME AS "Driver Fullname",
    D.LIC_DOB AS DOB,
    D.LIC_STREET || ' ' || LIC_TOWN || ' ' || LIC_POSTCODE AS "Driver Address",
    TO_CHAR(S.SUS_DATE, 'DD/MON/YY') AS "Suspended On",
    TO_CHAR(S.SUS_ENDDATE, 'DD/MON/YY') AS "Suspended Till"
FROM 
    DRIVER D
JOIN 
    SUSPENSION S
ON
    D.LIC_NO = S.LIC_NO
WHERE 
    SUS_DATE >= ADD_MONTHS(SYSDATE, -30)
ORDER BY
    D.LIC_NO ASC,
    SUS_DATE DESC;

/*
2(iv) Query 4
*/
--PLEASE PLACE REQUIRED SQL STATEMENT FOR THIS PART HERE

SELECT
    D.DEM_CODE AS "Demerit Code",
    D.DEM_DESCRIPTION AS "Demerit Descriptions",
    COUNT(TO_CHAR(O.OFF_DATETIME, 'MON')) AS "Total Offences (All Months)",
    EXTRACT(MONTH FROM O.OFF_DATETIME) AS JAN,
    EXTRACT(MONTH FROM O.OFF_DATETIME) AS FEB
FROM 
    OFFENCE O
JOIN 
    DEMERIT D
ON
    O.DEM_CODE = D.DEM_CODE
WHERE 
    TO_CHAR(O.OFF_DATETIME, 'MON') = 'JAN' OR
    TO_CHAR(O.OFF_DATETIME, 'MON') = 'FEB'
    
GROUP BY
    D.DEM_CODE,
    D.DEM_DESCRIPTION,
    EXTRACT(MONTH FROM O.OFF_DATETIME);
    --TO_CHAR(O.OFF_DATETIME, 'MON');
    --COUNT(TO_CHAR(O.OFF_DATETIME, 'MON'));





SELECT 
    --OFF_LOCATION,
    MONTH(OFF_DATETIME) [month]
    --TO_CHAR(OFF_DATETIME, 'YYYY'),
    --COUNT(OFF_NO)
FROM 
    OFFENCE
WHERE 
    OFF_DATETIME IS NOT NULL
GROUP BY
    MONTH(OFF_DATETIME)

    OFF_LOCATION,
    TO_CHAR(OFF_DATETIME, 'YYYY');











/*
2(v) Query 5
*/
--PLEASE PLACE REQUIRED SQL STATEMENT FOR THIS PART HERE


SELECT
    V.VEH_MANUFNAME AS "Manufacturer Name",
    COUNT(O.OFF_NO) AS "Total No. of Offences",
    sum(DEM_POINTS) 
FROM 
    OFFENCE O
JOIN 
    VEHICLE V
USING
    (VEH_VIN)
JOIN 
    DEMERIT D
ON
    O.DEM_CODE = D.DEM_CODE
GROUP BY
    VEH_MANUFNAME
HAVING
    COUNT(DEM_POINTS) >= 2
ORDER BY
    "Total No. of Offences" DESC,
    V.VEH_MANUFNAME ASC;







SELECT
    V.VEH_MANUFNAME AS "Manufacturer Name",
    COUNT(O.OFF_NO) AS "Total No. of Offences"
FROM 
    OFFENCE O
JOIN 
    VEHICLE V
USING
    (VEH_VIN)
JOIN 
    DEMERIT D
ON
    O.DEM_CODE = D.DEM_CODE
WHERE
    D.DEM_POINTS >= 2
GROUP BY
    VEH_MANUFNAME
ORDER BY
    "Total No. of Offences" DESC,
    V.VEH_MANUFNAME ASC;

select * from offence;
/*
2(vi) Query 6
*/
--PLEASE PLACE REQUIRED SQL STATEMENT FOR THIS PART HERE





/*
2(vii) Query 7
*/
--PLEASE PLACE REQUIRED SQL STATEMENT FOR THIS PART HERE





/*
2(viii) Query 8
*/
--PLEASE PLACE REQUIRED SQL STATEMENT FOR THIS PART HERE

























